<?php

use Application\Entity\Perfil as PerfilEntity;
?>
<div class="col-lg-10">
    <br /><br />
    <?php
    echo $this->form()->openTag($this->formVinculo);
    # hidden perfil
    echo $this->formElement($this->formVinculo->get('idPerfil'));
    # nome
    echo $this->formLabel($this->formVinculo->get('idLogin'));
    echo $this->formElement($this->formVinculo->get('idLogin'));
    # botao de incluir
    echo "<br />";
    echo $this->formElement($this->formVinculo->get('btnVincular'));
    ?>
    <div class="clearfix"></div>
    <br />
    <hr>
    <div id="usuarioVinculado" class="<?php echo (!$this->perfil->getIdLogin()->count()) ? 'hide' : '' ?>">
        <label><p>Usuário que já estão vinculados ao perfil.</p></label>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Usuário</th>
                    <th>Login</th>
                    <th>Situação</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                <?php
                if ($this->perfil->getIdLogin()->count()) :
                    foreach ($this->perfil->getIdLogin() as $login) :
                        ?>
                        <tr>
                            <td><?php echo $login->getIdPessoaFisica()->getDsNome(); ?></td>
                            <td><?php echo $login->getDsLogin(); ?></td>
                            <td><?php echo PerfilEntity::$arrSituacao[$login->getInAtivo()]; ?></td>
                            <td>
                                <i class="fa fa-remove" data-usuario="<?php echo $login->getIdLogin(); ?>" title="Remover Usuário" style="cursor: pointer"></i>
                            </td>
                        </tr>
                        <?php
                    endforeach;
                endif;
                ?>
            </tbody>
        </table>
    </div>
</div>
<br />
<br />
<?php
$this->headScript()->prependFile($this->basePath('module/perfil/js/vincular-usuario.js'));
