<?php
use Application\Entity\Empreendimento as EmpreendimentoEntity;

foreach ($this->register as $register) : ?>
    <tr>
        <td><?php echo $register->getDsEmpreendimento(); ?></td>
        <td><?php echo $register->getDsBairro(); ?></td>
        <td><?php echo $register->getIdMunicipio()->getIdEstado()->getDsSigla(); ?></td>
        <td><?php echo $register->getIdMunicipio()->getDsNome(); ?></td>
        <td><?php echo $register->getSituacao(); ?></td>
        <td>
            <?php if ($register->getSituacao()) : ?>
                <a href="<?php echo $this->url('empreendimento-obra', array('action' => 'edit', 'idEmpreendimento' => $register->getIdEmpreendimento())); ?>" style="cursor: pointer; color: #000;">
                    <i class="fa fa-edit" title="Editar" data-empreendimento="<?php echo $register->getIdEmpreendimento(); ?>" style="cursor: pointer;"></i>
                </a>
                <i class="fa fa-toggle-on" title="Inativar" data-empreendimento="<?php echo $register->getIdEmpreendimento(); ?>" style="cursor: pointer;"></i>
            <?php else : ?>
                <i class="fa fa-toggle-off" title="Ativar" data-empreendimento="<?php echo $register->getIdEmpreendimento(); ?>" style="cursor: pointer;"></i>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>