<?php
$strTitle = 'Edição dos dados do Empreendimento';
echo $this->headTitle($this->translate('SHOME :: ' . $strTitle));
?>
<div class="col-md-12">
    <h3 class="text-center"><?php echo $strTitle; ?></h3>
    <div>
        <?php
        echo $this->form()->openTag($this->form);
        ?>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-8">
                <?php
                echo $this->formLabel($this->form->get('dsEmpreendimento'));
                echo $this->formElement($this->form->get('dsEmpreendimento'));
                ?>                
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-3 col-sm-3 col-md-3">
                <?php
                echo $this->formLabel($this->form->get('coCep'));
                echo $this->formElement($this->form->get('coCep'));
                ?>                
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
                <?php
                echo $this->formLabel($this->form->get('coEstado'));
                echo $this->formElement($this->form->get('coEstado'));
                ?>                
            </div>
            <div class="col-xs-5 col-sm-5 col-md-5">
                <?php
                echo $this->formLabel($this->form->get('coMunicipio'));
                echo $this->formElement($this->form->get('coMunicipio'));
                ?>                
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-8">
                <?php
                echo $this->formLabel($this->form->get('dsLogradouro'));
                echo $this->formElement($this->form->get('dsLogradouro'));
                ?>                
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <?php
                echo $this->formLabel($this->form->get('dsBairro'));
                echo $this->formElement($this->form->get('dsBairro'));
                ?>                
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <?php
                echo $this->formLabel($this->form->get('dsComplemento'));
                echo $this->formElement($this->form->get('dsComplemento'));
                ?>                
            </div>
        </div>
        <br />
        <div class="pull-right">
            <div class="col-md-12">
                <div class="col-md-6">
                    <?php
                    # botao de salvar
                    echo $this->formElement($this->form->get('btnVoltar'));
                    ?>
                </div>
                <div class="col-md-6">
                    <?php
                    # botao de salvar
                    echo $this->formElement($this->form->get('btnSalvar'));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
    $this->headScript()
        ->prependFile($this->basePath('module/corezend/js/busca-cep.js'))
        ->prependFile($this->basePath('module/obra/js/busca-cep-municipio.js'))
        ->prependFile($this->basePath('module/obra/js/manter-empreendimento.js'));
